## Netlify build settings
[build]
  publish = "_site"
  command = "eleventy"

## Cache control for CSS files
[[headers]]
  for = "/assets/css/*.css"
  [headers.values]
    cache-control = '''
    public,
    max-age=1209600'''

## Opt out of Google's FLoC
[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"

## Special page redirects
[[redirects]]
  from = "/design"
  to = "/designs"
[[redirects]]
  from = "/shirts"
  to = "/designs"
[[redirects]]
  from = "/posters"
  to = "/designs"
[[redirects]]
  from = "/art"
  to = "/designs"

## Uses redirect
[[redirects]]
  from = "/uses"
  to = "/acknowledgements#uses"

[[redirects]]
  from = "/fr/usages"
  to = "/fr/remerciements/#usages"

## Error 404 redirects
[[redirects]]
  from = "/fr/*"
  to = "/fr/404.html"
  status = 404

[[redirects]]
  from = "/*"
  to = "/en/404.html"
  status = 404