backend:
  name: github
  repo: chriskirknielsen/2020
  branch: dev # Branch to update (optional; defaults to master)

# Uncomment below to enable drafts
# publish_mode: editorial_workflow

media_folder: "_includes/assets/img" # Media files will be stored in the repo under images/uploads

collections:
  # Our blog posts
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Summary", name: "summary", widget: "text", required: false }
      - { label: "Original", name: "original", widget: "string", required: false, description: "Link to the original content" }
      - { label: "Language", name: "language", widget: "select", options: ["en","fr"], default: "en" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Body", name: "body", widget: "markdown" }
  
  # Our pages e.g. About
  - name: "pages"
    label: "Page"
    folder: "pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Permalink", name: "permalink", widget: "string" }
      - { label: "Navigation Title", name: "navtitle", widget: "string" }
      - { label: "Language", name: "language", widget: "select", options: ["en","fr"], default: "en" }
      - { label: "Tags", name: "tags", widget: "hidden", default: "nav" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "globals"
    label: "Globals"
    files:
      - label: "Theme Settings"
        name: "theme"
        file: "src/_data/tokens.json"
        delete: false
        editor: 
          preview: false
        fields:
          - label: "Colours"
            name: "colors"
            widget: "object"
            fields: 
              - label: "Dusk"
                name: "dusk"
                widget: "object"
                fields:
                  - label: "Grey"
                    name: "grey"
                    widget: "object"
                    fields:
                      - {label: "Minimum", name: "min", widget: "string", default: "#e6e6e6"}
                      - {label: "Medium", name: "med", widget: "string", default: "#808080"}
                      - {label: "Maximum", name: "max", widget: "string", default: "#161616"}
                  - label: "Primary"
                    name: "primary"
                    widget: "object"
                    fields:
                      - {label: "Minimum", name: "min", widget: "string", default: "#e6e6e6"}
                      - {label: "Medium", name: "med", widget: "string", default: "#808080"}
                      - {label: "Maximum", name: "max", widget: "string", default: "#161616"}
                  - label: "Secondary"
                    name: "secondary"
                    widget: "object"
                    fields:
                      - {label: "Minimum", name: "min", widget: "string", default: "#e6e6e6"}
                      - {label: "Medium", name: "med", widget: "string", default: "#808080"}
                      - {label: "Maximum", name: "max", widget: "string", default: "#161616"}
              - label: "Dawn"
                name: "dusk"
                widget: "object"
                fields:
                  - label: "Grey"
                    name: "grey"
                    widget: "object"
                    fields:
                      - {label: "Minimum", name: "min", widget: "string", default: "#161616"}
                      - {label: "Medium", name: "med", widget: "string", default: "#808080"}
                      - {label: "Maximum", name: "max", widget: "string", default: "#e6e6e6"}
                  - label: "Primary"
                    name: "primary"
                    widget: "object"
                    fields:
                      - {label: "Minimum", name: "min", widget: "string", default: "#161616"}
                      - {label: "Medium", name: "med", widget: "string", default: "#808080"}
                      - {label: "Maximum", name: "max", widget: "string", default: "#e6e6e6"}
                  - label: "Secondary"
                    name: "secondary"
                    widget: "object"
                    fields:
                      - {label: "Minimum", name: "min", widget: "string", default: "#161616"}
                      - {label: "Medium", name: "med", widget: "string", default: "#808080"}
                      - {label: "Maximum", name: "max", widget: "string", default: "#e6e6e6"}
          - label: "Fonts"
            name: "fonts"
            widget: "object"
            fields: 
              - label: "Heading Font"
                name: "heading"
                widget: "object"
                fields:
                  - {label: "Main", name: "main", widget: "string", default: "null"}
                  - {label: "Fallback List", name: "fallback", widget: "select", options: ['sans','serif','mono'], default: "sans"}
              - label: "Body Font"
                name: "body"
                widget: "object"
                fields:
                  - {label: "Main", name: "main", widget: "string", default: "null"}
                  - {label: "Fallback List", name: "fallback", widget: "select", options: ['sans','serif','mono'], default: "sans"}
              - label: "Code Font"
                name: "code"
                widget: "object"
                fields:
                  - {label: "Main", name: "main", widget: "string", default: "null"}
                  - {label: "Fallback List", name: "fallback", widget: "select", options: ['sans','serif','mono'], default: "mono"}
          