backend:
  name: github
  repo: chriskirknielsen/2020
  branch: dev # Branch to update (optional; defaults to master)

# Uncomment below to enable drafts
# publish_mode: editorial_workflow

media_folder: "src/_includes/assets/img" # Media files will be stored in the repo under images/uploads

collections:
  # Our blog posts
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Summary", name: "summary", widget: "text", required: false }
      - { label: "Original", name: "original", widget: "string", required: false, description: "Link to the original content" }
      - { label: "Language", name: "language", widget: "select", options: ["en","fr"], default: "en" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Body", name: "body", widget: "markdown" }
  
  # Our pages e.g. About
  - name: "pages"
    label: "Page"
    folder: "pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Permalink", name: "permalink", widget: "string" }
      - { label: "Navigation Title", name: "navtitle", widget: "string" }
      - { label: "Language", name: "language", widget: "select", options: ["en","fr"], default: "en" }
      - { label: "Tags", name: "tags", widget: "hidden", default: "nav" }
      - { label: "Body", name: "body", widget: "markdown" }
  
  - name: "globals"
    label: "Globals"
    files:
      - label: "Theme Settings"
        name: "theme"
        file: "src/_data/tokens.json"
        delete: false
        editor: 
          preview: false
        fields:
          - label: "Colours"
            name: "colors"
            widget: "object"
            fields: 
              - label: "Dusk"
                name: "dusk"
                widget: "object"
                fields:
                  - label: "Grey"
                    name: "grey"
                    widget: "object"
                    fields:
                      - {label: "Minimum", name: "min", widget: "string", default: "#e6e6e6"}
                      - {label: "Medium", name: "med", widget: "string", default: "#808080"}
                      - {label: "Maximum", name: "max", widget: "string", default: "#161616"}
                  - label: "Primary"
                    name: "primary"
                    widget: "object"
                    fields:
                      - {label: "Minimum", name: "min", widget: "string", default: "#e6e6e6"}
                      - {label: "Medium", name: "med", widget: "string", default: "#808080"}
                      - {label: "Maximum", name: "max", widget: "string", default: "#161616"}
                  - label: "Secondary"
                    name: "secondary"
                    widget: "object"
                    fields:
                      - {label: "Minimum", name: "min", widget: "string", default: "#e6e6e6"}
                      - {label: "Medium", name: "med", widget: "string", default: "#808080"}
                      - {label: "Maximum", name: "max", widget: "string", default: "#161616"}
              - label: "Dawn"
                name: "dusk"
                widget: "object"
                fields:
                  - label: "Grey"
                    name: "grey"
                    widget: "object"
                    fields:
                      - {label: "Minimum", name: "min", widget: "string", default: "#161616"}
                      - {label: "Medium", name: "med", widget: "string", default: "#808080"}
                      - {label: "Maximum", name: "max", widget: "string", default: "#e6e6e6"}
                  - label: "Primary"
                    name: "primary"
                    widget: "object"
                    fields:
                      - {label: "Minimum", name: "min", widget: "string", default: "#161616"}
                      - {label: "Medium", name: "med", widget: "string", default: "#808080"}
                      - {label: "Maximum", name: "max", widget: "string", default: "#e6e6e6"}
                  - label: "Secondary"
                    name: "secondary"
                    widget: "object"
                    fields:
                      - {label: "Minimum", name: "min", widget: "string", default: "#161616"}
                      - {label: "Medium", name: "med", widget: "string", default: "#808080"}
                      - {label: "Maximum", name: "max", widget: "string", default: "#e6e6e6"}
          - label: "Fonts"
            name: "fonts"
            widget: "object"
            fields: 
              - label: "Heading Font"
                name: "heading"
                widget: "object"
                fields:
                  - {label: "Main", name: "main", widget: "string", default: "null"}
                  - {label: "Fallback List", name: "fallback", widget: "select", options: ['sans','serif','mono'], default: "sans"}
              - label: "Body Font"
                name: "body"
                widget: "object"
                fields:
                  - {label: "Main", name: "main", widget: "string", default: "null"}
                  - {label: "Fallback List", name: "fallback", widget: "select", options: ['sans','serif','mono'], default: "sans"}
              - label: "Code Font"
                name: "code"
                widget: "object"
                fields:
                  - {label: "Main", name: "main", widget: "string", default: "null"}
                  - {label: "Fallback List", name: "fallback", widget: "select", options: ['sans','serif','mono'], default: "mono"}
      
      - label: "English Localisation 🇬🇧"
        name: "locale_en"
        file: "src/en/en.json"
        delete: false
        editor: 
          preview: false
        fields:
          - label: "Locale"
            name: "locale"
            widget: "hidden"
            default: "en"
          - label: "Path"
            name: "localePath"
            widget: "hidden"
            default: "/"
          - label: "Root"
            name: "localeRoot"
            widget: "hidden"
            default: ""
          - label: "RSS permalink"
            name: "localeRssUrl"
            widget: "hidden"
            default: "/rss.xml"
          - label: "Punctuation Space"
            name: "punctSp"
            widget: "hidden"
            default: ""
          - label: "Navbar Pages"
            name: "dateFormat"
            widget: "list"
            default: ["home", "blog", "about", "contact"]
          - label: "Date Format"
            name: "dateFormat"
            widget: "string"
            default: "DD MMMM Y"
          - label: "Localised Strings"
            name: "localisedContent"
            widget: "object"
            fields:
              - label: "Skip to content"
                name: "skiplink"
                widget: "string"
                default: "Skip to content"
              - label: "Homepage"
                name: "logoLink"
                widget: "string"
                default: "Homepage"
              - label: "RSS Feed"
                name: "feed"
                widget: "object"
                fields:
                  - label: "Feed Subtitle"
                    name: "subtitle"
                    widget: "string"
                    default: "Blog of a front-end developer who likes to tinker"
              - label: "Latest Post"
                name: "latestPost"
                widget: "string"
                default: "Latest Post"
              - label: "Tagged"
                name: "tagged"
                widget: "string"
                default: "Tagged"
              - label: "Read Original"
                name: "original"
                widget: "string"
                default: "Read the original article"
              - label: "Read Full Article"
                name: "external"
                widget: "string"
                default: "Read the full article on"
              - label: "Homepage Mark Greeting"
                name: "homeMarkGreeting"
                widget: "string"
                default: "Hey, I'm"
              - label: "Homepage Mark Creative Developer"
                name: "homeMarkCreaDev"
                widget: "string"
                default: "Creative Developer"
              - label: "Homepage Mark Creative Developer Markup"
                name: "homeMarkCreaDevMarkup"
                widget: "string"
                default: "CRE<tspan>A</tspan>TIVE DEVELOPER"
              - label: "All Rights Reserved"
                name: "allRights"
                widget: "string"
                default: "All rights reserved"
              - label: "Language"
                name: "langLabel"
                widget: "string"
                default: "Language"
              - label: "If you found a mistake, would you kindly fix it?"
                name: "fixErrorPR"
                widget: "string"
                default: "If you found a mistake, would you kindly fix it?"
              - label: "Find me on these other sites"
                name: "externalLinks"
                widget: "string"
                default: "Find me on these other sites"
              - label: "Subscribe to chriskirknielsen's RSS feed"
                name: "rssHint"
                widget: "string"
                default: "Subscribe to chriskirknielsen's RSS feed"
          - label: "Switch Languages"
            name: "langSwitchLabel"
            widget: "string"
            default: "Switch Languages"
          - label: "Toggle Colour Scheme"
            name: "schemeSwitchLabel"
            widget: "string"
            default: "Toggle Colour Scheme"

      - label: "French Localisation 🇫🇷"
        name: "locale_en"
        file: "src/en/en.json"
        delete: false
        editor: 
          preview: false
        fields:
          - label: "Locale"
            name: "locale"
            widget: "hidden"
            default: "fr"
          - label: "Path"
            name: "localePath"
            widget: "hidden"
            default: "/fr/"
          - label: "Root"
            name: "localeRoot"
            widget: "hidden"
            default: "fr/"
          - label: "RSS permalink"
            name: "localeRssUrl"
            widget: "hidden"
            default: "/fr/rss.xml"
          - label: "Punctuation Space"
            name: "punctSp"
            widget: "hidden"
            default: " "
          - label: "Navbar Pages"
            name: "dateFormat"
            widget: "list"
            default: ["accueil", "blog", "a-propos", "contact"]
          - label: "Date Format"
            name: "dateFormat"
            widget: "string"
            default: "DD MMMM Y"
          - label: "Localised Strings"
            name: "localisedContent"
            widget: "object"
            fields:
              - label: "Skip to content"
                name: "skiplink"
                widget: "string"
                default: "Sauter au contenu"
              - label: "Homepage"
                name: "logoLink"
                widget: "string"
                default: "Page d'accueil"
              - label: "RSS Feed"
                name: "feed"
                widget: "object"
                fields:
                  - label: "Feed Subtitle"
                    name: "subtitle"
                    widget: "string"
                    default: "Blog d'un développeur front-end qui aime bidouiller"
              - label: "Latest Post"
                name: "latestPost"
                widget: "string"
                default: "Dernier Article"
              - label: "Tagged"
                name: "tagged"
                widget: "string"
                default: "Etiquettes"
              - label: "Read Original"
                name: "original"
                widget: "string"
                default: "Consulter l'article original"
              - label: "Read Full Article"
                name: "external"
                widget: "string"
                default: "Consulter l'article complet sur"
              - label: "Homepage Mark Greeting"
                name: "homeMarkGreeting"
                widget: "string"
                default: "Salut, moi c'est"
              - label: "Homepage Mark Creative Developer"
                name: "homeMarkCreaDev"
                widget: "string"
                default: "Développeur créatif"
              - label: "Homepage Mark Creative Developer Markup"
                name: "homeMarkCreaDevMarkup"
                widget: "string"
                default: "DÉVELOPPEUR CRÉ<tspan>A</tspan>TIF"
              - label: "All Rights Reserved"
                name: "allRights"
                widget: "string"
                default: "Tous droits réservés"
              - label: "Language"
                name: "langLabel"
                widget: "string"
                default: "Langue"
              - label: "If you found a mistake, would you kindly fix it?"
                name: "fixErrorPR"
                widget: "string"
                default: "Si vous avez repéré une erreur, puis-je vous demander de bien vouloir la corriger ?"
              - label: "Find me on these other sites"
                name: "externalLinks"
                widget: "string"
                default: "Retrouvez-moi sur ces autres sites"
              - label: "Subscribe to chriskirknielsen's RSS feed"
                name: "rssHint"
                widget: "string"
                default: "S'inscrire au flux RSS de chriskirknielsen"
          - label: "Switch Languages"
            name: "langSwitchLabel"
            widget: "string"
            default: "Changer de Langue"
          - label: "Toggle Colour Scheme"
            name: "schemeSwitchLabel"
            widget: "string"
            default: "Permuter la Palette de Couleurs"
